### PR TITLE
print status to stderr and add mode to just print urls to stdout

### PR DESCRIPTION
**Pull request by max-mapper**
it lets me do this for parallel downloading:

```
~/src/js/himawari.js/tmp 🐈  himawari --zoom=5 --urls | xargs nugget -c
Creating undefined in /Users/max/src/js/himawari.js/tmp ...
Downloading 050000_2_5.png
[=======================================>     ] 91.1% of 510.54 kB (11.02 kB/s)
Downloading 050000_2_8.png
[=================>                           ] 41.8% of 527.14 kB (4.86 kB/s)
Downloading 050000_2_9.png
[=======================================>     ] 89.5% of 500.58 kB (11.46 kB/s)
Downloading 050000_2_11.png
[===========================================> ] 97.9% of 506.16 kB (7.44 kB/s)
Downloading 050000_2_12.png
[===========================================> ] 98.1% of 560.04 kB (19.62 kB/s)
Downloading 050000_2_14.png
[===================>                         ] 46.3% of 504.01 kB (3.5 kB/s)
Downloading 050000_2_15.png
[>                                            ] 0.0% of 520.6 kB (0 B/s)
Downloading 050000_3_4.png
[===============>                             ] 37.4% of 637 kB (5.6 kB/s)
Downloading 050000_3_5.png
[=================================>           ] 76.6% of 641.74 kB (16.22 kB/s)
Downloading 050000_3_10.png
[================================>            ] 74.9% of 512.47 kB (11.89 kB/s)
Downloading 050000_3_12.png
[===============>                             ] 37.6% of 533.32 kB (540.88 B/s)
Downloading 050000_3_15.png
[========================>                    ] 55.8% of 543.05 kB (12.65 kB/s)
Downloading 050000_3_17.png
[========================================>    ] 91.6% of 278.81 kB (10.13 kB/s)
Downloading 050000_4_2.png
[============================>                ] 66.2% of 448.84 kB (37.15 kB/s)
Downloading 050000_4_3.png
[===============================>             ] 71.2% of 489.58 kB (12.63 kB/s)
Downloading 050000_4_5.png
[====================>                        ] 48.2% of 592.29 kB (1.42 kB/s)
Downloading 050000_4_6.png
[==============================>              ] 70.5% of 522.01 kB (7.97 kB/s)
Downloading 050000_4_7.png
[================>                            ] 39.5% of 602.71 kB (1.53 kB/s)

... and 381 more

Combined Speed: 175.63 kB/s
```

### CODE REVIEW

**Comment by max-mapper** [comment]
(doesnt integrate with the mosaic step but i might send another pr for that in the future)

**Comment by jakiestfu** [comment]
Thank you so much for your willingness to contribute! Couple questions, though.
1. Why log those informative pieces to stderr?
2. Async.js is used heavily in this project. There are some weird things going on under the hood of himawari.js that seemingly disable its ability to parallelize downloads, but using something like 'async.map' might yield better results. Would you want to try that instead?

**Comment by ungoldman** [comment]
@jakiestfu I think switching from stdout to stderr for those info messages makes it so that piping works more predictably (nothing is piped except the URLs). @maxogden Might I suggest something like `--urls-only` so that only errors are piped to stderr, but your use case it also supported?

Perhaps another (maybe even better) alternative is to create a standalone module that handles fetching and returning the URLs that support the needs of `himawari.js` and @maxogden's experiments.

**Comment by ungoldman** [comment]
I'm going to take a crack at making a `himawari-urls` module that fits the needs of this module and @maxogden's use case based off of @jakiestfu's work. Will let you know when it's published.

**Comment by ungoldman** [comment]
Okay I made the thing: https://github.com/ngoldman/himawari-urls

``` js
var himawariURLs = require('himawari-urls')

himawariURLs({
  date: 'latest',
  infrared: true,
  zoom: 1
}, function (err, tiles) {
  if (err) console.error(err)
  tiles.map(function (t) { console.log(t) })
})

// { name: '0_0.png',
//  url: 'http://himawari8-dl.nict.go.jp/himawari8/img/INFRARED_FULL/1d/550/2016/02/10/192000_0_0.png',
//  x: 0,
//  y: 0 }
```

**Comment by ungoldman** [comment]
@maxogden `himawari.js` now supports parallelized downloads with the `-p` flag (`himawari-bg` is parallel by default), and `himawari-urls` supports your use case.

However I don't think it's a bad idea to support the above use case. @jakiestfu would you accept a PR that only prints urls to stdout then exits and silences all other non-error output?

**Comment by jakiestfu** [comment]
@ngoldman All I'd have to do is provide the URL in the chunk callback and you can push those to an array. I could consider doing a "dry" feature/flag where no downloads are actually executed too.

Thoughts?

**Comment by ungoldman** [comment]
@jakiestfu I think that would work. So the desired outcome would be something like:

``` js
var himawari = require('himawari')

himawari({
  dry: true,
  chunk: function (info) {
    console.log(info.url)
  }
})
```

```
$ himawari --zoom 2 --dry
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/4d/550/2016/02/17/222000_0_0.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/4d/550/2016/02/17/222000_0_1.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/4d/550/2016/02/17/222000_0_2.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/4d/550/2016/02/17/222000_0_3.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/4d/550/2016/02/17/222000_1_0.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/4d/550/2016/02/17/222000_1_1.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/4d/550/2016/02/17/222000_1_2.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/4d/550/2016/02/17/222000_1_3.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/4d/550/2016/02/17/222000_2_0.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/4d/550/2016/02/17/222000_2_1.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/4d/550/2016/02/17/222000_2_2.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/4d/550/2016/02/17/222000_2_3.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/4d/550/2016/02/17/222000_3_0.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/4d/550/2016/02/17/222000_3_1.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/4d/550/2016/02/17/222000_3_2.png
http://himawari8-dl.nict.go.jp/himawari8/img/D531106/4d/550/2016/02/17/222000_3_3.png
```

right?

**Comment by jakiestfu** [comment]
Version `1.3.2` now supports `urls` flag for only printing URLs :)

**Pull request closed without merging**
